# Generated by Django 4.2.5 on 2023-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joinUs',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
