# Generated by Django 4.2.5 on 2023-11-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_joinus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='joinUs',
            new_name='joins',
        ),
    ]
