# Generated by Django 4.2.5 on 2023-11-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_joinus_profile_joins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='joins',
            new_name='join',
        ),
    ]
