# Generated by Django 4.2.5 on 2023-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_joins_profile_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join',
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default=1, max_length=233),
            preserve_default=False,
        ),
    ]
