# Generated by Django 4.2.5 on 2023-11-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_join_profile_type_of_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type_of_person',
        ),
    ]
