# Generated by Django 4.2.5 on 2023-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_profile_type_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default=1, max_length=233),
            preserve_default=False,
        ),
    ]
