# Generated by Django 4.2.5 on 2023-11-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_doctor_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor_section',
            field=models.CharField(choices=[('TOOTHS', 'TOOTHS'), ('MOUSE', 'MOUSE'), ('ANIMALS', 'ANIMALS')], max_length=60),
        ),
    ]
