# Generated by Django 4.2.5 on 2023-11-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_doctor_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor_section',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_of_person',
        ),
    ]
