# Generated by Django 4.2.5 on 2023-11-13 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0015_cat_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('who_I', models.TextField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('type_of_person', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=233)),
                ('doctor_section', models.CharField(choices=[('ANIMALS', 'ANIMALS'), ('MOUSE', 'MOUSE'), ('TOOTHS', 'TOOTHS')], max_length=60)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
